#!/usr/bin/env ruby

require 'tmpdir'
require 'fileutils'
require 'time'

def exec(cmd)
  abort("Error encountered, aborting") unless system(cmd)
end

puts "CI=#{ENV['CI']}"
puts "CI_DEPLOY=#{ENV['CI_DEPLOY']}"
puts "VIMEO_API_TOKEN=#{ENV['VIMEO_API_TOKEN'] && "*****" || ""}"
puts

# Forcing a change to the root directory, if not there already
Dir.chdir(File.absolute_path(File.join(File.dirname(__FILE__), "..")))

puts "---------------------------------------------------------------------"
puts "Compiling documentation (via mdoc) ..."
puts 

exec("rm -rf docs/")
exec("sbt -J-XX:MetaspaceSize=2g -J-XX:MaxMetaspaceSize=2g -J-Xmx4g mdoc")

puts "---------------------------------------------------------------------"
puts "Updating mtimes ..."
puts 

updated = 0
Dir["_docs/**/*.md"].each do |file|
  mt = `git log --pretty=format:%cd -n 1 --date=iso -- #{file}`
  unless mt
    mt = File.mtime(file)
  else 
    mt = Time.parse(mt)
  end
  rel_path = file.sub(/^_docs\//, "docs/")
  if File.file?(rel_path)
    FileUtils.touch rel_path, :mtime => mt
    updated += 1
  end
end

puts "Updated: #{updated}"
puts

puts "---------------------------------------------------------------------"
puts "Building with Jekyll ..."
puts 

exec("bundle exec jekyll build")

unless ENV['CI_DEPLOY'] == "true"
  puts "Skipping deployment, exiting..."
  exit 0
end

repository = "github.com/monix/monix.io.git"
ghToken = ENV['GH_TOKEN']

unless ghToken
  puts "Missing GH_TOKEN environment value!"
  exit 1
end

puts "---------------------------------------------------------------------"
puts "Deploying ..."
puts 

destDir = Dir.mktmpdir + "/" + "monix.io"
begin
  puts "Synchronizing gh-pages branch!"

  exec("rm -rf \"#{destDir}\"")
  exec("git clone \"https://#{ghToken}@#{repository}\" \"#{destDir}\" -b gh-pages")
  exec("rsync --filter='P .*' --delete-excluded -Pacv _site/ \"#{destDir}/\"")

  Dir.chdir(destDir) do |path|
    exec("git add .")
    exec('git config user.name "Alexandru Nedelcu"')
    exec('git config user.email "noreply@alexn.org"')
    exec('git commit -m "docs: update gh-pages"')
    exec("git push --force --quiet \"https://alexandru:#{ghToken}@#{repository}\" gh-pages:gh-pages")
  end
ensure
  exec("rm -rf \"#{destDir}\"")
end
