name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: "adopt@1.11"

      - name: Set up Ruby 2.7.1 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.1

      - name: Cache Ruby Bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: v4-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            v4-${{ runner.os }}-gems-

      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.cache/coursier
          key: v4-${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Install dependencies
        run: |
          # sudo apt-get install libgsl-dev
          # gem update --system
          # gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build
        run: |
          ./scripts/build
        env:
          VIMEO_API_TOKEN: ${{ secrets.VIMEO_API_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_DEPLOY: "true"
