name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@master

      - uses: olafurpg/setup-scala@v5
        with:
          java-version: "adopt@1.11"

      - name: Set up Ruby 2.6 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache Ruby Bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: v2-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            v2-${{ runner.os }}-gems-

      - name: Cache SBT Coursier
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/coursier
          key: v2-${{ runner.os }}-sbt-coursier-${{ hashFiles('**/build.sbt') }}

      - name: Install dependencies
        run: |
          sudo apt-get install libgsl-dev
          gem update --system
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          sbt update
          
      - name: Build
        run: |
          ./.github/scripts/build
        env:
          VIMEO_API_TOKEN: ${{ secrets.VIMEO_API_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_DEPLOY: "true"
